// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NorthfieldCMS.API.Data;

#nullable disable

namespace NorthfieldCMS.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261009100331_InitialCollegeManagementMigration")]
    partial class InitialCollegeManagementMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("NorthfieldCMS.API.Models.AttendanceRecord", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Course")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double>("Percentage")
                        .HasColumnType("REAL");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AttendanceId");

                    b.ToTable("AttendanceRecords");
                });

            modelBuilder.Entity("NorthfieldCMS.API.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Credits")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Faculty")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            Code = "CS301",
                            Credits = 4,
                            Department = "Computer Science",
                            Faculty = "Dr. Meera Shah",
                            Name = "Database Management Systems",
                            Semester = "Semester 5",
                            Status = "Active"
                        },
                        new
                        {
                            CourseId = 2,
                            Code = "CS302",
                            Credits = 4,
                            Department = "Computer Science",
                            Faculty = "Dr. Meera Shah",
                            Name = "Operating Systems",
                            Semester = "Semester 5",
                            Status = "Active"
                        },
                        new
                        {
                            CourseId = 3,
                            Code = "CS303",
                            Credits = 3,
                            Department = "Computer Science",
                            Faculty = "Dr. Kavita Rao",
                            Name = "Web Technologies",
                            Semester = "Semester 5",
                            Status = "Active"
                        },
                        new
                        {
                            CourseId = 4,
                            Code = "IT201",
                            Credits = 4,
                            Department = "Information Technology",
                            Faculty = "Dr. Kavita Rao",
                            Name = "Computer Networks",
                            Semester = "Semester 3",
                            Status = "Active"
                        },
                        new
                        {
                            CourseId = 5,
                            Code = "EC401",
                            Credits = 4,
                            Department = "Electronics Engineering",
                            Faculty = "Dr. S. Iyer",
                            Name = "Digital Signal Processing",
                            Semester = "Semester 7",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("NorthfieldCMS.API.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoursesCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HeadOfDepartment")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentsCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            CoursesCount = 12,
                            HeadOfDepartment = "Dr. Meera Shah",
                            Name = "Computer Science",
                            Status = "Active",
                            StudentsCount = 428
                        },
                        new
                        {
                            DepartmentId = 2,
                            CoursesCount = 10,
                            HeadOfDepartment = "Dr. Kavita Rao",
                            Name = "Information Technology",
                            Status = "Active",
                            StudentsCount = 316
                        },
                        new
                        {
                            DepartmentId = 3,
                            CoursesCount = 9,
                            HeadOfDepartment = "Dr. S. Iyer",
                            Name = "Electronics Engineering",
                            Status = "Active",
                            StudentsCount = 274
                        },
                        new
                        {
                            DepartmentId = 4,
                            CoursesCount = 8,
                            HeadOfDepartment = "Dr. Ananya Sen",
                            Name = "Business Administration",
                            Status = "Active",
                            StudentsCount = 218
                        },
                        new
                        {
                            DepartmentId = 5,
                            CoursesCount = 6,
                            HeadOfDepartment = "Dr. Vivek Menon",
                            Name = "Mathematics",
                            Status = "Active",
                            StudentsCount = 152
                        });
                });

            modelBuilder.Entity("NorthfieldCMS.API.Models.Exam", b =>
                {
                    b.Property<int>("ExamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Course")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxMarks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ExamId");

                    b.ToTable("Exams");

                    b.HasData(
                        new
                        {
                            ExamId = 1,
                            Course = "CS301 - DBMS",
                            Date = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = "2 Hours",
                            ExamName = "Mid Semester Exam",
                            MaxMarks = 50,
                            Status = "Scheduled",
                            Subject = "Database Management Systems",
                            Time = "10:00 AM"
                        },
                        new
                        {
                            ExamId = 2,
                            Course = "CS302 - OS",
                            Date = new DateTime(2026, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = "2 Hours",
                            ExamName = "Mid Semester Exam",
                            MaxMarks = 50,
                            Status = "Scheduled",
                            Subject = "Operating Systems",
                            Time = "02:00 PM"
                        },
                        new
                        {
                            ExamId = 3,
                            Course = "CS303 - Web Tech",
                            Date = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = "3 Hours",
                            ExamName = "Practical Evaluation",
                            MaxMarks = 25,
                            Status = "Scheduled",
                            Subject = "Web Technologies",
                            Time = "10:00 AM"
                        });
                });

            modelBuilder.Entity("NorthfieldCMS.API.Models.Faculty", b =>
                {
                    b.Property<int>("FacultyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FacultyCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FacultyId");

                    b.ToTable("FacultyMembers");

                    b.HasData(
                        new
                        {
                            FacultyId = 1,
                            Department = "Computer Science",
                            Email = "meera.shah@northfield.edu",
                            Experience = "12 Years",
                            FacultyCode = "FAC-001",
                            Name = "Dr. Meera Shah",
                            Specialization = "Machine Learning, DBMS",
                            Status = "Active"
                        },
                        new
                        {
                            FacultyId = 2,
                            Department = "Information Technology",
                            Email = "kavita.rao@northfield.edu",
                            Experience = "9 Years",
                            FacultyCode = "FAC-002",
                            Name = "Dr. Kavita Rao",
                            Specialization = "Cybersecurity, Cloud",
                            Status = "Active"
                        },
                        new
                        {
                            FacultyId = 3,
                            Department = "Electronics Engineering",
                            Email = "nikhil.joshi@northfield.edu",
                            Experience = "7 Years",
                            FacultyCode = "FAC-003",
                            Name = "Prof. Nikhil Joshi",
                            Specialization = "VLSI, Embedded Systems",
                            Status = "Inactive"
                        },
                        new
                        {
                            FacultyId = 4,
                            Department = "Electronics Engineering",
                            Email = "s.iyer@northfield.edu",
                            Experience = "14 Years",
                            FacultyCode = "FAC-004",
                            Name = "Dr. S. Iyer",
                            Specialization = "Signal Processing",
                            Status = "Active"
                        },
                        new
                        {
                            FacultyId = 5,
                            Department = "Business Administration",
                            Email = "ananya.sen@northfield.edu",
                            Experience = "10 Years",
                            FacultyCode = "FAC-005",
                            Name = "Dr. Ananya Sen",
                            Specialization = "Strategic Management",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("NorthfieldCMS.API.Models.FeeRecord", b =>
                {
                    b.Property<int>("FeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Course")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PendingAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalFees")
                        .HasColumnType("TEXT");

                    b.HasKey("FeeId");

                    b.ToTable("FeeRecords");

                    b.HasData(
                        new
                        {
                            FeeId = 1,
                            Course = "B.Tech CSE - Semester 5",
                            DueDate = new DateTime(2026, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaidAmount = 85000m,
                            PendingAmount = 0m,
                            Status = "Paid",
                            StudentName = "Riya Mehta",
                            TotalFees = 85000m
                        },
                        new
                        {
                            FeeId = 2,
                            Course = "B.Tech CSE - Semester 5",
                            DueDate = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaidAmount = 68000m,
                            PendingAmount = 17000m,
                            Status = "Partial",
                            StudentName = "Kirtan Barot",
                            TotalFees = 85000m
                        },
                        new
                        {
                            FeeId = 3,
                            Course = "B.Tech IT - Semester 3",
                            DueDate = new DateTime(2026, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaidAmount = 80000m,
                            PendingAmount = 0m,
                            Status = "Paid",
                            StudentName = "Aditi Sharma",
                            TotalFees = 80000m
                        });
                });

            modelBuilder.Entity("NorthfieldCMS.API.Models.MarkResult", b =>
                {
                    b.Property<int>("MarkResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExamMarks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InternalMarks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalMarks")
                        .HasColumnType("INTEGER");

                    b.HasKey("MarkResultId");

                    b.ToTable("MarkResults");

                    b.HasData(
                        new
                        {
                            MarkResultId = 1,
                            ExamMarks = 62,
                            Grade = "A+",
                            InternalMarks = 28,
                            Status = "Passed",
                            StudentName = "Riya Mehta",
                            Subject = "Database Management Systems",
                            TotalMarks = 90
                        },
                        new
                        {
                            MarkResultId = 2,
                            ExamMarks = 56,
                            Grade = "A",
                            InternalMarks = 25,
                            Status = "Passed",
                            StudentName = "Riya Mehta",
                            Subject = "Operating Systems",
                            TotalMarks = 81
                        },
                        new
                        {
                            MarkResultId = 3,
                            ExamMarks = 51,
                            Grade = "B+",
                            InternalMarks = 23,
                            Status = "Passed",
                            StudentName = "Riya Mehta",
                            Subject = "Web Technologies",
                            TotalMarks = 74
                        },
                        new
                        {
                            MarkResultId = 4,
                            ExamMarks = 60,
                            Grade = "A",
                            InternalMarks = 26,
                            Status = "Passed",
                            StudentName = "Kirtan Barot",
                            Subject = "Database Management Systems",
                            TotalMarks = 86
                        });
                });

            modelBuilder.Entity("NorthfieldCMS.API.Models.Material", b =>
                {
                    b.Property<int>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("MaterialId");

                    b.ToTable("Materials");

                    b.HasData(
                        new
                        {
                            MaterialId = 1,
                            FileType = "PDF",
                            Subject = "Database Management Systems",
                            Title = "DBMS Unit 3 — Relational Algebra Notes",
                            UploadedBy = "Dr. Meera Shah",
                            UploadedDate = new DateTime(2026, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaterialId = 2,
                            FileType = "DOCX",
                            Subject = "Operating Systems",
                            Title = "OS CPU Scheduling Lab Guide",
                            UploadedBy = "Dr. Meera Shah",
                            UploadedDate = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaterialId = 3,
                            FileType = "PPTX",
                            Subject = "Web Technologies",
                            Title = "Web Tech — React JS Slides",
                            UploadedBy = "Dr. Kavita Rao",
                            UploadedDate = new DateTime(2026, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("NorthfieldCMS.API.Models.NotificationRecord", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bg")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsUnread")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetAudience")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("NotificationId");

                    b.ToTable("NotificationRecords");

                    b.HasData(
                        new
                        {
                            NotificationId = 1,
                            Bg = "rgba(141,123,255,.16)",
                            Body = "The mid-semester timetable for B.Tech Semester 5 is now live. Exams start Aug 20.",
                            Ic = "#8d7bff",
                            Icon = "calendar-event",
                            IsUnread = true,
                            TargetAudience = "All",
                            Time = "10 mins ago",
                            Title = "Mid-Semester Exam Schedule Published"
                        },
                        new
                        {
                            NotificationId = 2,
                            Bg = "rgba(245,158,11,.15)",
                            Body = "Second installment of tuition fees is due on 30 August 2026.",
                            Ic = "#f59e0b",
                            Icon = "credit-card",
                            IsUnread = true,
                            TargetAudience = "Students",
                            Time = "2 hours ago",
                            Title = "Fee Payment Reminder"
                        },
                        new
                        {
                            NotificationId = 3,
                            Bg = "rgba(34,211,238,.12)",
                            Body = "Department review meeting in Seminar Hall B regarding NBA accreditation.",
                            Ic = "#22d3ee",
                            Icon = "people",
                            IsUnread = false,
                            TargetAudience = "Faculty",
                            Time = "Yesterday",
                            Title = "Faculty Meeting Today at 4 PM"
                        });
                });

            modelBuilder.Entity("NorthfieldCMS.API.Models.PasswordResetOtp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PasswordResetOtps");
                });

            modelBuilder.Entity("NorthfieldCMS.API.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AttendancePercentage")
                        .HasColumnType("REAL");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            AttendancePercentage = 92.5,
                            Department = "Computer Science",
                            Email = "riya.mehta@northfield.edu",
                            Name = "Riya Mehta",
                            Semester = "Semester 5",
                            Status = "Active",
                            StudentCode = "STU-2024-001"
                        },
                        new
                        {
                            StudentId = 2,
                            AttendancePercentage = 88.0,
                            Department = "Computer Science",
                            Email = "kirtan.barot@northfield.edu",
                            Name = "Kirtan Barot",
                            Semester = "Semester 5",
                            Status = "Active",
                            StudentCode = "STU-2024-002"
                        },
                        new
                        {
                            StudentId = 3,
                            AttendancePercentage = 95.0,
                            Department = "Information Technology",
                            Email = "aditi.sharma@northfield.edu",
                            Name = "Aditi Sharma",
                            Semester = "Semester 3",
                            Status = "Active",
                            StudentCode = "STU-2024-003"
                        },
                        new
                        {
                            StudentId = 4,
                            AttendancePercentage = 78.400000000000006,
                            Department = "Electronics Engineering",
                            Email = "dev.malhotra@northfield.edu",
                            Name = "Dev Malhotra",
                            Semester = "Semester 7",
                            Status = "Active",
                            StudentCode = "STU-2024-004"
                        },
                        new
                        {
                            StudentId = 5,
                            AttendancePercentage = 81.200000000000003,
                            Department = "Business Administration",
                            Email = "harsh.mehta@northfield.edu",
                            Name = "Harsh Mehta",
                            Semester = "Semester 1",
                            Status = "Active",
                            StudentCode = "STU-2024-005"
                        });
                });

            modelBuilder.Entity("NorthfieldCMS.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2024, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Administration",
                            Email = "admin@northfield.edu",
                            FullName = "Aarav Patel",
                            IsActive = true,
                            PasswordHash = "$2a$11$KDt1JeSelReBn2NuOOOZWOoOD2epPdSCkzuCB.1C9gZOmZLCUyQB2",
                            Role = "Admin"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2024, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Computer Science",
                            Email = "meera.shah@northfield.edu",
                            FullName = "Dr. Meera Shah",
                            IsActive = true,
                            PasswordHash = "$2a$11$2LGwlZ4fOxBjIX96p74OreFUxdwpcBhH6O9evcHkJF1x13IPgwfFW",
                            Role = "Faculty"
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Computer Science",
                            Email = "riya.mehta@northfield.edu",
                            FullName = "Riya Mehta",
                            IsActive = true,
                            PasswordHash = "$2a$11$cuvg/FToBh2KswPM0PmL3.oogYD9AhXBJHxmIJN4TXXmFEMciSSr.",
                            Role = "Student"
                        },
                        new
                        {
                            UserId = 4,
                            CreatedAt = new DateTime(2024, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Information Technology",
                            Email = "kavita.rao@northfield.edu",
                            FullName = "Dr. Kavita Rao",
                            IsActive = true,
                            PasswordHash = "$2a$11$2LGwlZ4fOxBjIX96p74OreFUxdwpcBhH6O9evcHkJF1x13IPgwfFW",
                            Role = "Faculty"
                        },
                        new
                        {
                            UserId = 5,
                            CreatedAt = new DateTime(2024, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Electronics Engineering",
                            Email = "nikhil.joshi@northfield.edu",
                            FullName = "Prof. Nikhil Joshi",
                            IsActive = false,
                            PasswordHash = "$2a$11$2LGwlZ4fOxBjIX96p74OreFUxdwpcBhH6O9evcHkJF1x13IPgwfFW",
                            Role = "Faculty"
                        },
                        new
                        {
                            UserId = 6,
                            CreatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Computer Science",
                            Email = "kirtan.barot@northfield.edu",
                            FullName = "Kirtan Barot",
                            IsActive = true,
                            PasswordHash = "$2a$11$cuvg/FToBh2KswPM0PmL3.oogYD9AhXBJHxmIJN4TXXmFEMciSSr.",
                            Role = "Student"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
